<?php
declare(strict_types=1);
final class FinalAssessmentService {
 private PDO $db;private OpenAIClient $openai;
 public function __construct(PDO $db,OpenAIClient $openai){$this->db=$db;$this->openai=$openai;}
 public function finalize(int $sessionId,int $userId):array {
  $st=$this->db->prepare('SELECT * FROM interview_sessions WHERE id=?');$st->execute([$sessionId]);$session=$st->fetch();if(!$session)throw new InvalidArgumentException('미팅 질문지를 찾을 수 없습니다.');$answers=$this->db->prepare('SELECT question_key,answer FROM interview_answers WHERE interview_session_id=?');$answers->execute([$sessionId]);$answerRows=$answers->fetchAll();if(!$answerRows)throw new InvalidArgumentException('서술형 답변을 먼저 입력해 주세요.');
  $docs=$this->db->prepare("SELECT company_id,grant_program_id,analysis_json FROM documents WHERE analysis_status='completed' AND (company_id=? OR grant_program_id=?) ORDER BY analyzed_at DESC");$docs->execute([$session['company_id'],$session['grant_program_id']]);$context=['questions'=>json_decode($session['questions_json'],true),'answers'=>$answerRows,'document_analyses'=>$docs->fetchAll()];
  $scoreItem=['type'=>'object','additionalProperties'=>false,'required'=>['area','score','level','evidence','gap'],'properties'=>['area'=>['type'=>'string'],'score'=>['type'=>'number','minimum'=>0,'maximum'=>100],'level'=>['type'=>'string'],'evidence'=>['type'=>'string'],'gap'=>['type'=>'string']]];
  $schema=['type'=>'object','additionalProperties'=>false,'required'=>['eligibility_passed','interview_score','current_scorecard','improvement_plan','to_be','kpis','reasons','risks'],'properties'=>['eligibility_passed'=>['type'=>'boolean'],'interview_score'=>['type'=>'number','minimum'=>0,'maximum'=>100],'current_scorecard'=>['type'=>'array','minItems'=>5,'items'=>$scoreItem],'improvement_plan'=>['type'=>'array','items'=>['type'=>'object','additionalProperties'=>false,'required'=>['priority','area','action','owner','timeframe','expected_effect'],'properties'=>['priority'=>['type'=>'integer'],'area'=>['type'=>'string'],'action'=>['type'=>'string'],'owner'=>['type'=>'string'],'timeframe'=>['type'=>'string'],'expected_effect'=>['type'=>'string']]]],'to_be'=>['type'=>'array','items'=>['type'=>'object','additionalProperties'=>false,'required'=>['area','current_state','target_state','target_date'],'properties'=>['area'=>['type'=>'string'],'current_state'=>['type'=>'string'],'target_state'=>['type'=>'string'],'target_date'=>['type'=>'string']]]],'kpis'=>['type'=>'array','items'=>['type'=>'object','additionalProperties'=>false,'required'=>['name','definition','unit','baseline','target','measurement_method','frequency','owner'],'properties'=>['name'=>['type'=>'string'],'definition'=>['type'=>'string'],'unit'=>['type'=>'string'],'baseline'=>['type'=>['number','null']],'target'=>['type'=>['number','null']],'measurement_method'=>['type'=>'string'],'frequency'=>['type'=>'string'],'owner'=>['type'=>'string']]]],'reasons'=>['type'=>'array','items'=>['type'=>'string']],'risks'=>['type'=>'array','items'=>['type'=>'string']]]];
  $result=$this->openai->structured('서술형 미팅 답변을 근거로 현재 기업 성적표(As-Is), 부족점, 우선순위별 개선과제, 목표상태(To-Be), KPI를 생성하세요. 답변에 없는 수치는 추측하지 말고 baseline과 target을 null로 두며 추가 측정이 필요하다고 명시하세요. 각 현재점수에는 반드시 답변 근거를 연결하세요. 공고 필수자격 충족 여부도 별도로 판정하세요.',$context,$schema,'company_scorecard');
  $diag=(float)$this->db->query('SELECT COALESCE(MAX(total_score),0) FROM diagnostics WHERE company_id='.(int)$session['company_id'])->fetchColumn();$match=(float)$this->db->query('SELECT COALESCE(MAX(total_score),0) FROM grant_matches WHERE company_id='.(int)$session['company_id'].' AND grant_program_id='.(int)$session['grant_program_id'])->fetchColumn();$interview=(float)$result['interview_score'];$final=round($diag*.30+$match*.30+$interview*.40,2);$decision=!$result['eligibility_passed']?'reject':($final>=80?'recommend':($final>=65?'conditional':($final>=50?'hold':'reject')));
  $actions=array_map(function($x){return $x['action'];},$result['improvement_plan']);$sql='INSERT INTO company_decisions(company_id,grant_program_id,interview_session_id,eligibility_passed,diagnostic_score,match_score,interview_score,final_score,decision,reasons_json,risks_json,required_actions_json,current_scorecard_json,improvement_plan_json,to_be_json,kpis_json,decided_at,decided_by)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,NOW(),?)';$ins=$this->db->prepare($sql);$encode=function($v){return json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);};$ins->execute([$session['company_id'],$session['grant_program_id'],$sessionId,$result['eligibility_passed']?1:0,$diag,$match,$interview,$final,$decision,$encode($result['reasons']),$encode($result['risks']),$encode($actions),$encode($result['current_scorecard']),$encode($result['improvement_plan']),$encode($result['to_be']),$encode($result['kpis']),$userId]);$decisionId=(int)$this->db->lastInsertId();$this->db->prepare("UPDATE interview_sessions SET status='evaluated',completed_at=NOW() WHERE id=?")->execute([$sessionId]);
  return ['decision_id'=>$decisionId,'eligibility_passed'=>$result['eligibility_passed'],'scores'=>['diagnostic'=>$diag,'match'=>$match,'interview'=>$interview,'final'=>$final],'decision'=>$decision,'reasons'=>$result['reasons'],'risks'=>$result['risks'],'current_scorecard'=>$result['current_scorecard'],'improvement_plan'=>$result['improvement_plan'],'to_be'=>$result['to_be'],'kpis'=>$result['kpis']];
 }
}
