<?php
declare(strict_types=1);
final class GoogleDriveClient {
 private array $config;private ?string $token=null;
 public function __construct(array $config){$this->config=$config;}
 public static function fileIdFromUrl(string $url):string {if(preg_match('~/d/([a-zA-Z0-9_-]+)~',$url,$m)||preg_match('~[?&]id=([a-zA-Z0-9_-]+)~',$url,$m))return $m[1];if(preg_match('~^[a-zA-Z0-9_-]{10,}$~',$url))return $url;throw new InvalidArgumentException('올바른 Google Drive 파일 링크가 아닙니다.');}
 private function accessToken():string {if($this->token)return $this->token;foreach(['client_id','client_secret','refresh_token']as$key)if(empty($this->config[$key]))throw new RuntimeException('Google OAuth 설정이 필요합니다.');$body=http_build_query(['client_id'=>$this->config['client_id'],'client_secret'=>$this->config['client_secret'],'refresh_token'=>$this->config['refresh_token'],'grant_type'=>'refresh_token']);$r=HttpClient::request('POST','https://oauth2.googleapis.com/token',['Content-Type: application/x-www-form-urlencoded'],$body);$j=json_decode($r['body'],true);if($r['status']!==200||empty($j['access_token']))throw new RuntimeException('Google OAuth 토큰 갱신 실패');return $this->token=$j['access_token'];}
 public function metadata(string $fileId):array {$fields='id,name,mimeType,size,modifiedTime,md5Checksum,webViewLink,capabilities(canDownload)';return HttpClient::json('GET','https://www.googleapis.com/drive/v3/files/'.rawurlencode($fileId).'?fields='.rawurlencode($fields),['Authorization: Bearer '.$this->accessToken()]);}
 public function downloadToTemp(array $meta,int $maxBytes):string {if(empty($meta['capabilities']['canDownload']))throw new RuntimeException('Drive에서 다운로드가 허용되지 않은 파일입니다.');if(isset($meta['size'])&&(int)$meta['size']>$maxBytes)throw new RuntimeException('파일 크기 제한을 초과했습니다.');$isGoogle=strpos((string)$meta['mimeType'],'application/vnd.google-apps.')===0;$url=$isGoogle?'https://www.googleapis.com/drive/v3/files/'.rawurlencode($meta['id']).'/export?mimeType=application%2Fpdf':'https://www.googleapis.com/drive/v3/files/'.rawurlencode($meta['id']).'?alt=media';$r=HttpClient::request('GET',$url,['Authorization: Bearer '.$this->accessToken()]);if($r['status']!==200)throw new RuntimeException('Drive 파일 다운로드 실패');if(strlen($r['body'])>$maxBytes)throw new RuntimeException('파일 크기 제한을 초과했습니다.');$path=tempnam(sys_get_temp_dir(),'compass_');if($path===false||file_put_contents($path,$r['body'],LOCK_EX)===false)throw new RuntimeException('임시 파일 생성 실패');chmod($path,0600);return $path;}
}
