<?php
declare(strict_types=1);
final class OpenAIClient {
 private array $config;
 public function __construct(array $config){$this->config=$config;if(empty($config['api_key']))throw new RuntimeException('OPENAI_API_KEY 설정이 필요합니다.');}
 private function auth():array{return ['Authorization: Bearer '.$this->config['api_key']];}
 public function upload(string $path,string $name,string $mime='application/pdf'):string {$ch=curl_init('https://api.openai.com/v1/files');curl_setopt_array($ch,[CURLOPT_POST=>true,CURLOPT_RETURNTRANSFER=>true,CURLOPT_TIMEOUT=>180,CURLOPT_HTTPHEADER=>$this->auth(),CURLOPT_POSTFIELDS=>['purpose'=>'user_data','file'=>new CURLFile($path,$mime,$name)]]);$raw=curl_exec($ch);$status=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE);if($raw===false){$e=curl_error($ch);curl_close($ch);throw new RuntimeException('OpenAI 파일 전송 실패: '.$e);}curl_close($ch);$j=json_decode($raw,true);if($status<200||$status>=300||empty($j['id']))throw new RuntimeException('OpenAI 파일 등록 실패');return $j['id'];}
 public function analyze(string $fileId,string $documentType):array {$schema=['type'=>'object','additionalProperties'=>false,'required'=>['document_type','summary','requirements','evaluation_criteria','exclusions','evidence','missing_information'],'properties'=>['document_type'=>['type'=>'string'],'summary'=>['type'=>'string'],'requirements'=>['type'=>'array','items'=>['type'=>'object','additionalProperties'=>false,'required'=>['category','condition','required'],'properties'=>['category'=>['type'=>'string'],'condition'=>['type'=>'string'],'required'=>['type'=>'boolean']]]],'evaluation_criteria'=>['type'=>'array','items'=>['type'=>'object','additionalProperties'=>false,'required'=>['name','weight','description'],'properties'=>['name'=>['type'=>'string'],'weight'=>['type'=>['number','null']],'description'=>['type'=>'string']]]],'exclusions'=>['type'=>'array','items'=>['type'=>'string']],'evidence'=>['type'=>'array','items'=>['type'=>'object','additionalProperties'=>false,'required'=>['field','page','quote'],'properties'=>['field'=>['type'=>'string'],'page'=>['type'=>['integer','null']],'quote'=>['type'=>'string']]]],'missing_information'=>['type'=>'array','items'=>['type'=>'string']]]];$payload=['model'=>$this->config['model'],'store'=>false,'input'=>[['role'=>'user','content'=>[['type'=>'input_file','file_id'=>$fileId],['type'=>'input_text','text'=>'이 문서는 '.$documentType.'입니다. 신청자격, 필수조건, 제외조건, 평가항목과 근거 페이지를 한국어로 추출하세요. 문서에 없는 내용은 추측하지 마세요.']]]],'text'=>['format'=>['type'=>'json_schema','name'=>'document_analysis','strict'=>true,'schema'=>$schema]]];$r=HttpClient::json('POST','https://api.openai.com/v1/responses',$this->auth(),$payload);$text=$r['output_text']??null;if(!$text&&isset($r['output']))foreach($r['output']as$item)foreach(($item['content']??[])as$content)if(isset($content['text'])){$text=$content['text'];break 2;}$data=json_decode((string)$text,true);if(!is_array($data))throw new RuntimeException('AI 분석 결과 형식이 올바르지 않습니다.');return ['data'=>$data,'response_id'=>$r['id']??null,'usage'=>$r['usage']??null];}
 public function deleteFile(string $fileId):void {try{HttpClient::json('DELETE','https://api.openai.com/v1/files/'.rawurlencode($fileId),$this->auth());}catch(Throwable $e){error_log('OpenAI temp file cleanup failed: '.$fileId);}}
 public function structured(string $instruction,array $context,array $schema,string $name):array {$payload=['model'=>$this->config['model'],'store'=>false,'input'=>[['role'=>'user','content'=>[['type'=>'input_text','text'=>$instruction."\n\nCONTEXT_JSON:\n".json_encode($context,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)]]]],'text'=>['format'=>['type'=>'json_schema','name'=>$name,'strict'=>true,'schema'=>$schema]]];$r=HttpClient::json('POST','https://api.openai.com/v1/responses',$this->auth(),$payload);$text=$r['output_text']??null;if(!$text&&isset($r['output']))foreach($r['output']as$item)foreach(($item['content']??[])as$content)if(isset($content['text'])){$text=$content['text'];break 2;}$data=json_decode((string)$text,true);if(!is_array($data))throw new RuntimeException('AI 구조화 결과 형식이 올바르지 않습니다.');return $data;}
}
