<?php
declare(strict_types=1);
try{require __DIR__.'/../app/bootstrap.php';$method=$_SERVER['REQUEST_METHOD'];$uri=trim((string)parse_url($_SERVER['REQUEST_URI'],PHP_URL_PATH),'/');$pos=strpos($uri,'api/');$route=$pos===false?'':substr($uri,$pos+4);
 if($route==='health'&&$method==='GET')jsonResponse(['ok'=>true,'version'=>'2.0']);
 if($route==='session'&&$method==='GET')jsonResponse(['authenticated'=>!empty($_SESSION['user_id']),'csrf'=>$_SESSION['csrf'],'user'=>$_SESSION['user']??null]);
 if($route==='login'&&$method==='POST'){$b=bodyJson();$st=$db->prepare('SELECT id,email,password_hash,name,role FROM users WHERE email=? AND is_active=1');$st->execute([strtolower(trim((string)($b['email']??'')))]);$u=$st->fetch();if(!$u||!password_verify((string)($b['password']??''),$u['password_hash']))jsonResponse(['error'=>'이메일 또는 비밀번호가 올바르지 않습니다.'],401);session_regenerate_id(true);$_SESSION['user_id']=(int)$u['id'];$_SESSION['user']=['email'=>$u['email'],'name'=>$u['name'],'role'=>$u['role']];$_SESSION['csrf']=bin2hex(random_bytes(32));$db->prepare('UPDATE users SET last_login_at=NOW() WHERE id=?')->execute([$u['id']]);audit($db,(int)$u['id'],'login');jsonResponse(['user'=>$_SESSION['user'],'csrf'=>$_SESSION['csrf']]);}
 $userId=requireAuth();if($method!=='GET')requireCsrf();
 if($route==='logout'&&$method==='POST'){audit($db,$userId,'logout');$_SESSION=[];session_destroy();jsonResponse(['ok'=>true]);}
 if($route==='companies'&&$method==='GET'){$st=$db->query('SELECT * FROM companies ORDER BY updated_at DESC');jsonResponse(['data'=>$st->fetchAll()]);}
 if($route==='companies'&&$method==='POST'){$name=trim((string)($_POST['name']??''));$industry=trim((string)($_POST['industry']??''));$grantId=(int)($_POST['grant_program_id']??0);if($name===''||$industry===''||$grantId<1)jsonResponse(['error'=>'기업명, 업종, 매칭할 공모는 필수입니다.'],422);$check=$db->prepare('SELECT id FROM grant_programs WHERE id=?');$check->execute([$grantId]);if(!$check->fetchColumn())jsonResponse(['error'=>'선택한 공모를 찾을 수 없습니다.'],422);$st=$db->prepare("INSERT INTO companies(name,industry,ceo_name,memo,stage)VALUES(?,?,?,?,'진단 진행')");$st->execute([$name,$industry,trim((string)($_POST['ceo']??'')),json_encode(['region'=>$_POST['region']??null,'size'=>$_POST['size']??null],JSON_UNESCAPED_UNICODE)]);$companyId=(int)$db->lastInsertId();$service=new DocumentAnalysisService($db,new OpenAIClient($config['openai']),(int)$config['security']['max_document_bytes']);$analyses=[];$errors=[];foreach(array_merge(uploadedFiles('company_docs'),uploadedFiles('financial_docs'))as$file){if(($file['error']??UPLOAD_ERR_NO_FILE)===UPLOAD_ERR_NO_FILE)continue;try{$analyses[]=$service->analyzeUpload($file,$companyId,null,$userId);}catch(Throwable$e){$errors[]=['name'=>$file['name']??'unknown','error'=>$e->getMessage()];}}$match=$db->prepare("INSERT INTO grant_matches(company_id,grant_program_id,eligibility,rule_score,semantic_score,total_score,matched_reasons,gaps_json)VALUES(?,?,'review',0,0,0,'[]','[]')");$match->execute([$companyId,$grantId]);audit($db,$userId,'company.create_match','company',$companyId,['grant_program_id'=>$grantId,'documents'=>count($analyses),'errors'=>count($errors)]);jsonResponse(['id'=>$companyId,'name'=>$name,'grant_program_id'=>$grantId,'match_id'=>(int)$db->lastInsertId(),'analyses'=>$analyses,'document_errors'=>$errors],201);}
 if($route==='grant-programs'&&$method==='POST'){$b=bodyJson();if(trim((string)($b['title']??''))===''||trim((string)($b['agency']??''))==='')jsonResponse(['error'=>'공고명과 주관기관은 필수입니다.'],422);$requirements=['eligibility'=>$b['eligibility']??'','required_documents'=>$b['required_documents']??''];$evaluation=['criteria'=>$b['criteria']??''];$st=$db->prepare('INSERT INTO grant_programs(title,agency,apply_end,requirements_json,evaluation_json)VALUES(?,?,?,?,?)');$st->execute([$b['title'],$b['agency'],$b['deadline']?:null,json_encode($requirements,JSON_UNESCAPED_UNICODE),json_encode($evaluation,JSON_UNESCAPED_UNICODE)]);$id=(int)$db->lastInsertId();audit($db,$userId,'grant.create','grant',$id);jsonResponse(['id'=>$id,'title'=>$b['title']],201);}
 if($route==='documents'&&$method==='GET'){$st=$db->query('SELECT id,company_id,grant_program_id,original_name,mime_type,file_size,content_hash,analysis_status,analysis_version,analyzed_at,error_message,created_at FROM documents ORDER BY updated_at DESC LIMIT 200');jsonResponse(['data'=>$st->fetchAll()]);}
 if($route==='documents/analyze-upload'&&$method==='POST'){$companyId=isset($_POST['company_id'])?(int)$_POST['company_id']:null;$grantId=isset($_POST['grant_program_id'])?(int)$_POST['grant_program_id']:null;if(($companyId===null)==($grantId===null))jsonResponse(['error'=>'기업 또는 공고 중 하나를 선택해 주세요.'],422);$service=new DocumentAnalysisService($db,new OpenAIClient($config['openai']),(int)$config['security']['max_document_bytes']);$result=$service->analyzeUpload($_FILES['document']??[],$companyId,$grantId,$userId);audit($db,$userId,'document.upload_analyze','document',$result['id'],['temporary_file_deleted'=>true]);jsonResponse($result,201);}
 if(preg_match('~^documents/(\d+)$~',$route,$m)&&$method==='GET'){$st=$db->prepare('SELECT * FROM documents WHERE id=?');$st->execute([(int)$m[1]]);$doc=$st->fetch();if(!$doc)jsonResponse(['error'=>'문서를 찾을 수 없습니다.'],404);$doc['analysis']=json_decode((string)$doc['analysis_json'],true);unset($doc['analysis_json']);jsonResponse(['data'=>$doc]);}
 if($route==='interviews/generate'&&$method==='POST'){$b=bodyJson();$service=new InterviewService($db,new OpenAIClient($config['openai']));$result=$service->generate((int)($b['company_id']??0),(int)($b['grant_program_id']??0),$userId);audit($db,$userId,'interview.generate','interview',$result['session_id']);jsonResponse($result,201);}
 if(preg_match('~^interviews/(\d+)/answers$~',$route,$m)&&$method==='POST'){$b=bodyJson();$service=new InterviewService($db,new OpenAIClient($config['openai']));$service->saveAnswers((int)$m[1],is_array($b['answers']??null)?$b['answers']:[]);audit($db,$userId,'interview.answers','interview',(int)$m[1]);jsonResponse(['ok'=>true]);}
 if(preg_match('~^interviews/(\d+)/finalize$~',$route,$m)&&$method==='POST'){$service=new FinalAssessmentService($db,new OpenAIClient($config['openai']));$result=$service->finalize((int)$m[1],$userId);audit($db,$userId,'interview.finalize','interview',(int)$m[1],['decision'=>$result['decision']]);jsonResponse($result);}
 if(preg_match('~^decisions/(\d+)$~',$route,$m)&&$method==='GET'){$st=$db->prepare('SELECT * FROM company_decisions WHERE id=?');$st->execute([(int)$m[1]]);$decision=$st->fetch();if(!$decision)jsonResponse(['error'=>'최종 판단을 찾을 수 없습니다.'],404);foreach(['reasons_json','risks_json','required_actions_json','current_scorecard_json','improvement_plan_json','to_be_json','kpis_json']as$key)$decision[str_replace('_json','',$key)]=json_decode((string)$decision[$key],true);jsonResponse(['data'=>$decision]);}
 jsonResponse(['error'=>'API를 찾을 수 없습니다.'],404);
}catch(InvalidArgumentException $e){if(function_exists('jsonResponse'))jsonResponse(['error'=>$e->getMessage()],422);http_response_code(422);header('Content-Type: application/json');echo json_encode(['error'=>$e->getMessage()]);}catch(Throwable $e){error_log($e->__toString());if(function_exists('jsonResponse'))jsonResponse(['error'=>'요청 처리 중 오류가 발생했습니다.'],500);http_response_code(500);header('Content-Type: application/json');echo json_encode(['error'=>'서비스 설정을 확인해 주세요.']);}
